### ISSUE TITLE
it authenticates the accounts then shows an error

### ISSUE THREAD

**Issue by Myshiro** [6uf/mcsn#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6d3f08]

goroutine 1 [running]:
github.com/6uf/apiGO.BuxDroptime({0x7fff7dda478a, 0x3})
        C:/Users/Brand/go/pkg/mod/github.com/6uf/api!g!o@v0.0.0-20220519175949-f                                                                              f7d912d22cb/mcsn.go:41 +0x88
github.com/6uf/apiGO.DropTime({0x7fff7dda478a, 0x3})
        C:/Users/Brand/go/pkg/mod/github.com/6uf/api!g!o@v0.0.0-20220519175949-f                                                                              f7d912d22cb/mcsn.go:64 +0x25
mcsn/src.Snipe({0x7fff7dda478a, 0x3}, 0x4000000000000000, {0x858c2f?, 0x0?}, {0x                                                                              0, 0x0})
        C:/Users/Brand/OneDrive/Desktop/mcsn-main-dev/mcsn/src/utils.go:69 +0x11                                                                              0
main.main.func1(0xc000092c60?)
        C:/Users/Brand/OneDrive/Desktop/mcsn-main-dev/mcsn/main.go:38 +0xa7
github.com/urfave/cli/v2.(*Command).Run(0xc000092c60, 0xc0001ea1c0)
        C:/Users/Brand/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/command.go:163                                                                               +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc000198340, {0x95aab8?, 0xc00002209                                                                              8}, {0xc00001e1e0, 0x6, 0x6})
        C:/Users/Brand/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:313 +0x                                                                              b48
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/Brand/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.main()
        C:/Users/Brand/OneDrive/Desktop/mcsn-main-dev/mcsn/main.go:388 +0x13db

**Comment by 6uf** [comment]
Im pretty sure that was because my website was down at the time. it should be resolved now.
